# Generated by Django 4.2.3 on 2023-08-02 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='corp_information',
            fields=[
                ('corp_code', models.IntegerField(db_column='corp_code', primary_key=True, serialize=False)),
                ('corp_name', models.CharField(db_column='corp_name', max_length=50)),
                ('corp_ind', models.CharField(db_column='corp_ind', max_length=50)),
                ('corp_sm', models.IntegerField(db_column='corp_sm')),
                ('corp_m', models.FloatField(db_column='corp_m')),
                ('corp_aug', models.FloatField(db_column='corp_aug')),
                ('corp_sal', models.IntegerField(db_column='corp_sal')),
                ('corp_sales', models.BigIntegerField(db_column='corp_sales')),
                ('corp_ope', models.BigIntegerField(db_column='corp_ope')),
                ('fin_gro', models.FloatField(db_column='fin_gro')),
                ('fin_sta', models.FloatField(db_column='fin_sta')),
                ('fin_pro', models.FloatField(db_column='fin_pro')),
                ('fin_act', models.FloatField(db_column='fin_act')),
                ('career', models.FloatField(db_column='career')),
                ('wl_balance', models.FloatField(db_column='wl_balance')),
                ('welfare', models.FloatField(db_column='welfare')),
                ('culture', models.FloatField(db_column='culture')),
                ('management', models.FloatField(db_column='management')),
                ('cluster', models.IntegerField(db_column='cluster')),
            ],
        ),
    ]
