# Generated by Django 4.2.3 on 2023-08-02 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Corp_info_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corp_information',
            old_name='career',
            new_name='CAREER',
        ),
        migrations.RenameField(
            model_name='corp_information',
            old_name='cluster',
            new_name='CLUSTER',
        ),
        migrations.RenameField(
            model_name='corp_information',
            old_name='corp_aug',
            new_name='CORP_AUG',
        ),
        migrations.RenameField(
            model_name='corp_information',
            old_name='corp_code',
            new_name='CORP_CODE',
        ),
        migrations.RenameField(
            model_name='corp_information',
            old_name='corp_ind',
            new_name='CORP_IND',
        ),
        migrations.RenameField(
            model_name='corp_information',
            old_name='corp_m',
            new_name='CORP_M',
        ),
        migrations.RenameField(
            model_name='corp_information',
            old_name='corp_name',
            new_name='CORP_NAME',
        ),
        migrations.RenameField(
            model_name='corp_information',
            old_name='corp_ope',
            new_name='CORP_OPE',
        ),
        migrations.RenameField(
            model_name='corp_information',
            old_name='corp_sal',
            new_name='CORP_SAL',
        ),
        migrations.RenameField(
            model_name='corp_information',
            old_name='corp_sales',
            new_name='CORP_SALES',
        ),
        migrations.RenameField(
            model_name='corp_information',
            old_name='corp_sm',
            new_name='CORP_SM',
        ),
        migrations.RenameField(
            model_name='corp_information',
            old_name='culture',
            new_name='CULTURE',
        ),
        migrations.RenameField(
            model_name='corp_information',
            old_name='fin_act',
            new_name='FIN_ACT',
        ),
        migrations.RenameField(
            model_name='corp_information',
            old_name='fin_gro',
            new_name='FIN_GRO',
        ),
        migrations.RenameField(
            model_name='corp_information',
            old_name='fin_pro',
            new_name='FIN_PRO',
        ),
        migrations.RenameField(
            model_name='corp_information',
            old_name='fin_sta',
            new_name='FIN_STA',
        ),
        migrations.RenameField(
            model_name='corp_information',
            old_name='management',
            new_name='MANAGEMENT',
        ),
        migrations.RenameField(
            model_name='corp_information',
            old_name='welfare',
            new_name='WELFARE',
        ),
        migrations.RenameField(
            model_name='corp_information',
            old_name='wl_balance',
            new_name='WL_BALANCE',
        ),
    ]
